version: '3.8'

services:
  aw:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: aw
    volumes: 
      - adventureworks-data:/var/opt/mssql
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PWD}

volumes:
  adventureworks-data:
    name: adventureworks-data